spring:
  datasource:
    url: jdbc:mysql://103.218.122.180:3306/cntt_master_qlbh2022
    username: trandat
    password: 123456789

  jpa:
    hibernate:
#        ddl-auto: none
      ddl-auto: update
#        ddl-auto: create-drop

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect


  security:
    oauth2:
      authorizationserver:
        client:
          client-1:
            registration:
              client-id: "admin-client"
              # the client secret is "secret" (without quotes)
              client-secret: "{bcrypt}$2a$10$jdJGhzsiIqYFpjJiYWMl/eKDOd8vdyQis2aynmFN0dgJ53XvpzzwC"
              client-authentication-methods: "client_secret_basic"
              authorization-grant-types: "client_credentials"
              scopes: "user.read,user.write"
