server:
  port: 8087

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2_security
    username: root
    password: 123456789

  jpa:
    hibernate:
      ddl-auto: update

#    open-in-view: false

#  security:
#    oauth2:
#      authorization-server:
#        client:
#          client-1:
#            registration:
#              client-id: "admin-client"
#              # the client secret is "secret" (without quotes)
#              client-secret: "{bcrypt}$2a$10$jdJGhzsiIqYFpjJiYWMl/eKDOd8vdyQis2aynmFN0dgJ53XvpzzwC"
#              client-authentication-methods: "client_secret_basic"
#              authorization-grant-types: "client_credentials"
#              scopes: "user.read,user.write"
